# Generated by Django 2.0.4 on 2018-05-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('birth', models.DateField()),
                ('region', models.CharField(max_length=30)),
                ('preference', models.CharField(max_length=255)),
                ('ddd', models.IntegerField()),
                ('whatsapp', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('howDidYouKnow', models.CharField(max_length=255)),
                ('want_ongs', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('volunteers', models.IntegerField()),
                ('limit', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField()),
                ('subscription', models.BooleanField(default=False)),
                ('call', models.BooleanField(default=False)),
                ('schedule', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activities',
            field=models.ManyToManyField(blank=True, to='general.Activity'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
