# Generated by Django 2.0.4 on 2018-05-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='institution',
            field=models.BooleanField(default=True),
        ),
    ]
