# Generated by Django 2.0.4 on 2018-05-21 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_activity_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='institution',
        ),
    ]
