# Generated by Django 2.0.4 on 2018-05-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_remove_activity_institution'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activity',
            new_name='HospitalActivity',
        ),
    ]
