# Generated by Django 2.0.4 on 2018-06-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalactivity',
            name='selected',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
