# Generated by Django 2.0.4 on 2018-06-17 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoactivity',
            name='prelist',
            field=models.ManyToManyField(blank=True, related_name='prelistNgo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalactivity',
            name='prelist',
            field=models.ManyToManyField(blank=True, related_name='prelist', to=settings.AUTH_USER_MODEL),
        ),
    ]
