# Generated by Django 2.0.4 on 2018-06-12 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalactivity',
            name='prelis',
            field=models.ManyToManyField(blank=True, related_name='prelis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalactivity',
            name='selected',
            field=models.ManyToManyField(blank=True, related_name='selected', to=settings.AUTH_USER_MODEL),
        ),
    ]
