# Generated by Django 2.0.4 on 2018-06-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0002_auto_20180612_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalactivity',
            name='selected',
        ),
        migrations.AddField(
            model_name='hospitalactivity',
            name='selected',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
