# Generated by Django 2.0.4 on 2018-06-17 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0002_auto_20180617_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngoactivity',
            name='novice_list',
        ),
    ]
