# Generated by Django 2.0.4 on 2018-06-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0003_auto_20180613_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalactivity',
            name='selected',
            field=models.CharField(max_length=1000),
        ),
    ]
