# Generated by Django 2.0.4 on 2018-06-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0004_auto_20180613_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalactivity',
            name='waiting',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='hospitalactivity',
            name='selected',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
