# Generated by Django 2.0.4 on 2018-05-30 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(20), django.core.validators.RegexValidator(code='invalid_username', flags=None, message='Username must be Alphanumeric', regex='^[a-zA-Z0-9]+([_-]?[a-zA-Z0-9])*$')])),
                ('password', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(32)])),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('cpf', models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)])),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator(regex='^[a-zA-Z]+([ ]?[a-zA-Z])*$')])),
                ('birth', models.DateField()),
                ('region', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30)])),
                ('preference', models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(40)])),
                ('ddd', models.IntegerField(validators=[django.core.validators.MinValueValidator(11), django.core.validators.MaxValueValidator(99), django.core.validators.RegexValidator(regex='((([1,4,6,8,9][1-9])|(2[1,2,4,7,8])|(3[1-8])|(4[1-9])|(5[1-5])|(7[1,3,4,5,7,9])))')])),
                ('whatsapp', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(9)])),
                ('address', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(80)])),
                ('genre', models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(20)])),
                ('howDidYouKnow', models.CharField(max_length=255)),
                ('want_ongs', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, django.core.validators.RegexValidator),
        ),
    ]
