# Generated by Django 2.0.4 on 2018-06-10 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(132), django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
