# Generated by Django 2.0.4 on 2018-05-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_api', '0001_initial'),
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activities',
            field=models.ManyToManyField(blank=True, to='activity_api.Activity'),
        ),
    ]
