# Generated by Django 2.0.4 on 2018-06-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inscrito',
            field=models.BooleanField(default=False),
        ),
    ]
