# Generated by Django 2.0.4 on 2018-06-01 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_userprofile_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='Novato', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ddd',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(99), django.core.validators.RegexValidator(regex='((([2,4,6,8,9][1-9])|(2[1,2,4,7,8])|(3[1-8])|(4[1-9])|(5[1-5])|(7[1,3,4,5,7,9])))')]),
        ),
    ]
